version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    env_file:
      - ./apps/server/.env.docker
    ports:
      - "3005:3005"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - ./apps/web/.env.docker
    ports:
      - "3000:3000"

  ws:
    build:
      context: .
      dockerfile: apps/ws/Dockerfile
    env_file:
      - ./apps/ws/.env.docker
    depends_on:
      - redis
    ports:
      - "5000:5000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres: 
    image: postgres:17
    container_name: postgres 
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: subhdeep
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: